name: Build and Push Docker Image

on:
  release:
    types:
      - published

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout pymumu/smartdns repository
      uses: actions/checkout@v2
      with:
        repository: pymumu/smartdns
        ref: ${{ github.event.release.target_commitish }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to Docker Hub
      run: docker login -u your-docker-username -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./smartdns   # 指定 smartdns 仓库的相对路径
        dockerfile: ./Dockerfile   # 指定 smartdns 仓库中的 Dockerfile 路径
        push: true
        tags: anyingiit/smartdns-docker:latest
